version: '3.0'

name: nihongo_ecom

services:
  web:
    build: .
    container_name: nihongo_ecom
    command: >
      bash -c " rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - .:/src/app
      - /app/tmp
      - bundle-data:/usr/local/bundle
    depends_on:
      - db
    links:
      - db:db
    stdin_open: true
    tty: true
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nihongo_ecom_development
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3310:3306"
    container_name: nihongo_ecom.database
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server
    container_name: nihongo_ecom.redis
    volumes:
      - redis-data:/var/shared/redis
volumes:
  mysql_data:
  bundle-data:
  redis-data:
